version: 2.1

orbs: 
  python: circleci/python@1.5.0

jobs:
  lint:
    resource_class: small
    docker:
      # Python runtime same as .python-version
      - image: cimg/python:3.8.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Lint Python files
          command: poetry run black --check .

  test:
    parallelism: 2
    docker:
      # Python runtime same as .python-version
      - image: cimg/python:3.8.12
      - image: cimg/postgres:10.19
        environment: # environment variables for database
          POSTGRES_USER: django
          POSTGRES_DB: sample_django
          # Passwords should not be commited like this ideally,
          # however, this is for a test DB
          POSTGRES_PASSWORD: 'unchained!'
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Confirm DB is up and ready
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 30s
      - run:
          name: Run DB schema migrations
          command: |
            poetry run python manage.py migrate
      - run:
          name: Run tests
          command: |
            # get test files while ignoring __init__ files
            TESTFILES=$(circleci tests glob "*/tests/*.py" | sed 's/\S\+__init__.py//g')
            echo $TESTFILES | tr ' ' '\n' | sort | uniq > circleci_test_files.txt
            cat circleci_test_files.txt
            TESTFILES=$(circleci tests split --split-by=timings circleci_test_files.txt)
            # massage filepaths into format manage.py test accepts
            TESTFILES=$(echo $TESTFILES | tr "/" "." | sed 's/\.py//g')
            echo $TESTFILES

            poetry run python manage.py test --failfast $TESTFILES

workflows:
  unchained:
    jobs:
      - lint
      - test:
          requires:
            - lint
